Mobile updates
UCSD-E4E/website2.0 pull request #125
Opened 2024-06-11 06:08 UTC by Sean1572

closes #20

2024-06-15 21:25 UTC, ntlhui commented
It'd be really cool to be able to swipe on the carousel

2024-06-15 21:26 UTC, ntlhui commented
I feel like the standard menu should be the hamburger icon?  not the arrow... but maybe that specifically an Android standard?

2024-06-15 21:28 UTC, ntlhui commented
![Screenshot_20240615-142719.png](https://github.com/UCSD-E4E/website2.0/assets/5642851/0735233d-03bf-446f-86c5-184cd8d4b329)

The menu spacing seems uneven

2024-06-15 21:31 UTC, ntlhui requested changes
See comments

2024-06-18 17:09 UTC, Sean1572 commented
> I feel like the standard menu should be the hamburger icon? not the arrow... but maybe that specifically an Android standard?

Technically speaking, the menu isn't a hamburger so an arrow is fine. I've seen arguments that hamburgers are more recognizable as menu icons. Either way I think we will be okay

2024-06-18 17:10 UTC, Sean1572 commented
> It'd be really cool to be able to swipe on the carousel

good idea

2024-06-18 17:24 UTC, Sean1572 commented
> ![Screenshot_20240615-142719.png](https://private-user-images.githubusercontent.com/5642851/340039439-0735233d-03bf-446f-86c5-184cd8d4b329.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MzE3NDIsIm5iZiI6MTcxODczMTQ0MiwicGF0aCI6Ii81NjQyODUxLzM0MDAzOTQzOS0wNzM1MjMzZC0wM2JmLTQ0NmYtODZjNS0xODRjZDhkNGIzMjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MThUMTcyNDAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjQwOGQwOTY3N2I0MTJiYjA2YTFkZTE5Y2M2MjE0M2FkNWE3ZjJkNzU4MDMwMGQ5MjQ3NzlkMDg3M2RkNDg5MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Ucg2lVnQDJAaF2JG31pbzyQfWXyDmHBmzMD8ZN-dvEA)
> 
> The menu spacing seems uneven

quick check, as in the spacing between menu items?

2024-06-20 01:56 UTC, ntlhui commented on assets/c.png
What is this for?

2024-06-20 18:04 UTC, ntlhui approved these changes

2024-06-21 04:17 UTC, merged