feat: landing page for info session
UCSD-E4E/website2.0 pull request #202
Opened 2024-10-04 02:24 UTC by Sean1572

2024-10-04 14:38 UTC, ntlhui commented
![image](https://github.com/user-attachments/assets/ba74bc5d-7810-42b9-996d-d4c0ba61f9f9)

QR Code: 
![image](https://github.com/user-attachments/assets/a5c5df0f-4286-4b62-b8eb-8eef9c22f233)

2024-10-04 14:38 UTC, ntlhui commented
Does it make sense to link the emails?  `[nthui@ucsd.edu](mailto:nthui@ucsd.edu)`

2024-10-04 14:41 UTC, ntlhui requested changes

2024-10-04 14:41 UTC, ntlhui commented on ayl.md
> +- Tyler Flar (Radio Telemetry Tracking) – tflar@ucsd.edu
Inconsistent formatting

2024-10-04 14:41 UTC, ntlhui commented on ayl.md
> +- Nathan Hui, nthui@ucsd.edu
Let's drop this, I've removed it as an option from the application, and I don't really have time to manage it.

2024-10-04 14:41 UTC, ntlhui commented on ayl.md
> +## [Radio Telemetry Tracking]({{ "acoustic-species-identification" | relative_url }})
Wrong text

2024-10-04 16:29 UTC, ccrutchf commented
Do we want to link the papers here?

2024-10-04 16:44 UTC, Sean1572 commented
I've linked project webpages, should we add a link to onboarding papers?

2024-10-04 17:45 UTC, Sean1572 commented
> ![image](https://private-user-images.githubusercontent.com/5642851/373681458-ba74bc5d-7810-42b9-996d-d4c0ba61f9f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNjQxMDcsIm5iZiI6MTcyODA2MzgwNywicGF0aCI6Ii81NjQyODUxLzM3MzY4MTQ1OC1iYTc0YmM1ZC03ODEwLTQyYjktOTk2ZC1kNGMwYmE2MWY5ZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDRUMTc0MzI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDI3YWU4NmRkNTNlYTcyNTkxMmMwZGYyZTlkYzZlZTE0NGZiZTQ1MDY4MjQ1M2M2ZGY0ZjA4ZDQ3NmQ5ZTE0NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.X0IeMb_DkCM7dqP1G2zW_9zKIQleRiORUubiQCOJkkM)
> 
> QR Code: ![image](https://private-user-images.githubusercontent.com/5642851/373682056-a5c5df0f-4286-4b62-b8eb-8eef9c22f233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwNjQxMDcsIm5iZiI6MTcyODA2MzgwNywicGF0aCI6Ii81NjQyODUxLzM3MzY4MjA1Ni1hNWM1ZGYwZi00Mjg2LTRiNjItYjhlYi04ZWVmOWMyMmYyMzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDRUMTc0MzI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDkwMzdkMWRkYzAxM2EyNGE5MmUyNWU3NmUyYzY5MzgyMzdkNWU4MzQ3OTVmNTJhMGM0YTViZmYxNmQwYjBhYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.KcZRfRxaNwvjUmGZG7ym-TglFJUPWbMW1X8LYEnbR3k)

check qr code, its ayl not qyl

2024-10-04 17:49 UTC, Sean1572 commented
![image](https://github.com/user-attachments/assets/7ca27fb8-53d6-4eed-bf25-18725494c3b6)

2024-10-08 21:47 UTC, TQZhang04 approved these changes
LGTM - Sean

2024-10-09 00:21 UTC, ntlhui approved these changes

2024-10-09 00:21 UTC, merged