Collapse abstracts
UCSD-E4E/website2.0 pull request #88
Opened 2024-05-17 23:05 UTC by Sean1572

2024-08-29 07:29 UTC, ntlhui reviewed
Source changes look good, @ntlhui to deploy local to review build

2024-08-30 21:42 UTC, Sean1572 commented
One big thing is maybe styling could use work

2024-09-24 01:38 UTC, ntlhui commented
The `+` is not immediately obvious.

Maybe a better styling might be an `Abstract` "button" between the citation and the DOI/HTTP/ArXiV links?

2024-09-24 03:47 UTC, Sean1572 commented
> The `+` is not immediately obvious.
> 
> Maybe a better styling might be an `Abstract` "button" between the citation and the DOI/HTTP/ArXiV links?

Interesting, let me take another look and maybe come up with a few ideas

2024-09-24 04:00 UTC, Sean1572 commented
> The `+` is not immediately obvious.
> 
> Maybe a better styling might be an `Abstract` "button" between the citation and the DOI/HTTP/ArXiV links?

Does this consider that hovering over the text makes the textbox highlighted and underlined?

2024-09-24 04:09 UTC, Sean1572 commented
![image](https://github.com/user-attachments/assets/c844f84a-3336-4df1-bdb6-0ad5f76d010f)

2025-01-11 01:22 UTC, ntlhui requested changes
Unable to demonstrate.

Chrome 131.0.6778.265 (Official Build) (64-bit) (cohort: Stable) 
Win 10
Local build
Ublock origin disabled.

Additionally, clicking on a lower entry causes navigation to top of page

2025-01-11 02:24 UTC, ntlhui requested changes
CI build is breaking, please resolve

2025-01-11 03:53 UTC, ntlhui commented
CI build is still failing

2025-03-25 07:31 UTC, Sean1572 commented
Last build fails are websites that working but are slow rn

2025-09-05 02:01 UTC, ccrutchf approved these changes

2025-09-05 02:07 UTC, merged